### ISSUE TITLE
新しくリポジトリを作成する

### ISSUE THREAD

**Issue by masayatoida** [masayatoida/MoneyCalcuator#1]
@fuchi0741

お疲れ様です。先日教えていただいた記事を参考にリポジトリを作成してみました。
できたと思うのですが、いかかがでしょうか？

![image](https://user-images.githubusercontent.com/74668904/116485537-68ca2000-a8c6-11eb-8e3f-99a6b7465356.png)

Last login: Thu Apr 29 08:28:19 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculator % git init
Initialized empty Git repository in /Users/rie/Desktop/MoneyCalculator/.git/
rie@toidarikounoMacBook-Pro MoneyCalculator % git add
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?
rie@toidarikounoMacBook-Pro MoneyCalculator % git add .
rie@toidarikounoMacBook-Pro MoneyCalculator % git commit -m "first commit"
[master (root-commit) b887729] first commit
 14 files changed, 712 insertions(+)
 create mode 100644 MoneyCalculator.xcodeproj/project.pbxproj
 create mode 100644 MoneyCalculator.xcodeproj/project.xcworkspace/contents.xcworkspacedata
 create mode 100644 MoneyCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
 create mode 100644 MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
 create mode 100644 MoneyCalculator.xcodeproj/xcuserdata/rie.xcuserdatad/xcschemes/xcschememanagement.plist
 create mode 100644 MoneyCalculator/AppDelegate.swift
 create mode 100644 MoneyCalculator/Assets.xcassets/AccentColor.colorset/Contents.json
 create mode 100644 MoneyCalculator/Assets.xcassets/AppIcon.appiconset/Contents.json
 create mode 100644 MoneyCalculator/Assets.xcassets/Contents.json
 create mode 100644 MoneyCalculator/Base.lproj/LaunchScreen.storyboard
 create mode 100644 MoneyCalculator/Base.lproj/Main.storyboard
 create mode 100644 MoneyCalculator/Info.plist
 create mode 100644 MoneyCalculator/SceneDelegate.swift
 create mode 100644 MoneyCalculator/ViewController.swift
rie@toidarikounoMacBook-Pro MoneyCalculator % git remote add origin https://github.com/masayatoida/MoneyCalcuator.git
rie@toidarikounoMacBook-Pro MoneyCalculator % git push -u origin master
Username for 'https://github.com':masayatoida                                 o Password for 'https://masayatoida@github.com': 
Enumerating objects: 29, done.
Counting objects: 100% (29/29), done.
Delta compression using up to 12 threads
Compressing objects: 100% (24/24), done.
Writing objects: 100% (29/29), 14.63 KiB | 4.88 MiB/s, done.
Total 29 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), done.
remote: 
remote: Create a pull request for 'master' on GitHub by visiting:
remote:      https://github.com/masayatoida/MoneyCalcuator/pull/new/master
remote: 
To https://github.com/masayatoida/MoneyCalcuator.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
rie@toidarikounoMacBook-Pro MoneyCalculator %

**Comment by fuchi0741** [comment]
@masayatoida 
お！できたのいい感じですね！素晴らしいです！
以下のようなファイルを追加していただきたいのですが、できそうでしょうか??
xcodeから新規プロジェクトを作成したタイミングで生成されるファイルです😆

<img width="909" alt="スクリーンショット 2021-04-30 15 43 35" src="https://user-images.githubusercontent.com/50318372/116658389-d495b100-a9ca-11eb-917a-60af1396eda2.png">

**Comment by fuchi0741** [comment]
@masayatoida コードもコピペもありがとうございます！
次からで大丈夫なのですが、コードをコピペする際は`マークダウン`を使用しましょう！
理由は単純で、見やすいからですmm


右上にある<>を
コピペしていただいたところに、すると以下のようにできますmm

色々あるので右上にあるやつ試してみると面白いかもです！

<img width="452" alt="スクリーンショット 2021-04-30 15 49 02" src="https://user-images.githubusercontent.com/50318372/116658851-96e55800-a9cb-11eb-84e5-7a946e4f7344.png">


```
Last login: Thu Apr 29 08:28:19 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculator % git init
Initialized empty Git repository in /Users/rie/Desktop/MoneyCalculator/.git/
rie@toidarikounoMacBook-Pro MoneyCalculator % git add
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?
rie@toidarikounoMacBook-Pro MoneyCalculator % git add .
rie@toidarikounoMacBook-Pro MoneyCalculator % git commit -m "first commit"
[master (root-commit) b887729] first commit
14 files changed, 712 insertions(+)
create mode 100644 MoneyCalculator.xcodeproj/project.pbxproj
create mode 100644 MoneyCalculator.xcodeproj/project.xcworkspace/contents.xcworkspacedata
create mode 100644 MoneyCalculator.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
create mode 100644 MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
create mode 100644 MoneyCalculator.xcodeproj/xcuserdata/rie.xcuserdatad/xcschemes/xcschememanagement.plist
create mode 100644 MoneyCalculator/AppDelegate.swift
create mode 100644 MoneyCalculator/Assets.xcassets/AccentColor.colorset/Contents.json
create mode 100644 MoneyCalculator/Assets.xcassets/AppIcon.appiconset/Contents.json
create mode 100644 MoneyCalculator/Assets.xcassets/Contents.json
create mode 100644 MoneyCalculator/Base.lproj/LaunchScreen.storyboard
create mode 100644 MoneyCalculator/Base.lproj/Main.storyboard
create mode 100644 MoneyCalculator/Info.plist
create mode 100644 MoneyCalculator/SceneDelegate.swift
create mode 100644 MoneyCalculator/ViewController.swift
rie@toidarikounoMacBook-Pro MoneyCalculator % git remote add origin https://github.com/masayatoida/MoneyCalcuator.git
rie@toidarikounoMacBook-Pro MoneyCalculator % git push -u origin master
Username for 'https://github.com':masayatoida o Password for 'https://masayatoida@github.com':
Enumerating objects: 29, done.
Counting objects: 100% (29/29), done.
Delta compression using up to 12 threads
Compressing objects: 100% (24/24), done.
Writing objects: 100% (29/29), 14.63 KiB | 4.88 MiB/s, done.
Total 29 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), done.
remote:
remote: Create a pull request for 'master' on GitHub by visiting:
remote: https://github.com/masayatoida/MoneyCalcuator/pull/new/master
remote:
To https://github.com/masayatoida/MoneyCalcuator.git

[new branch] master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.
rie@toidarikounoMacBook-Pro MoneyCalculator %
```

**Comment by masayatoida** [comment]
@fuchi0741 
マークダウン了解しました！

![image](https://user-images.githubusercontent.com/74668904/116984827-a1268f80-ad06-11eb-8b5a-8ca9533ee167.png)

追加の方法はわかったのですが２つのTest fileが見当たりません・・・

![image](https://user-images.githubusercontent.com/74668904/116985259-3033a780-ad07-11eb-96c8-cc826d72e78c.png)
ファイル作成時はこのように設定したのですが
調べたところinclude Unit Testにチェックを入れると載っていましたがないようで・・・

**Comment by fuchi0741** [comment]
@masayatoida 

> 調べたところinclude Unit Testにチェックを入れると載っていましたがないようで・・・

Xcodeのバージョンっていくつかわかりますか？

というのも、チェックボックスありますし、添付画像を見たことがないためです。
Xcodeの最新バージョンは12.5なのですが、12.5から変わったのかな？と予想しています。
それが上記の質問の意図です。

ちなみに自分はこのようになっておりチェックボックスが存在します。
バージョンは14.4です。
<img width="841" alt="スクリーンショット 2021-05-04 18 46 32" src="https://user-images.githubusercontent.com/50318372/116986689-0c716100-ad09-11eb-8ac8-a7c8018b971b.png">


ちなみにスクショの添付はGoodです！

ぜひ転職後も継続してください！

**Comment by fuchi0741** [comment]
あとテストコードは後回しでいいと思うため、一旦ファイルなくても大丈夫ですよ！
後から追加できるので！

テストコードは大事ですが、工数的に一旦スルーでいきましょう！

**Comment by masayatoida** [comment]
@fuchi0741 

![image](https://user-images.githubusercontent.com/74668904/116997051-40538300-ad17-11eb-95bf-c265e4136950.png)

12.4ですね・・・
とりあえずスルーしていきます。

**Comment by fuchi0741** [comment]
@masayatoida リポジトリ作成もできていそうなので、このissueも削除しましょう！
