### ISSUE TITLE
設計書を作成する

### ISSUE THREAD

**Issue by masayatoida** [masayatoida/MoneyCalcuator#2]
@fuchi0741

設計書を作成してみましたがいかかでしょうか？

![image](https://user-images.githubusercontent.com/74668904/116485838-2f45e480-a8c7-11eb-9dc1-458f3df77a1e.png)

**Comment by fuchi0741** [comment]
おお！見やすくていいですね！
## 1枚目
問題ないかと思います！
技術的な難易度もそこまで高くないかと思います！(デザインする必要はありますが、一旦あとで考えましょう！)
余談ですが、アプリを開いたとき最初に表示される画面のことをスプラッシュ画面と言います。
今回のアプリだと、この画面が相当します。

## 2枚目
左上にある一覧に戻るですが、一覧画面がない気がするのですが。。。
そもそも一覧画面と履歴画面の違いってなんでしょうか？

## 3枚目
右上の削除ボタンはどこまで削除できるのかがわからないです！
(おそらく各履歴のことだと思いますが、直感的にユーザはわからないのでは？と思い書きました。)

またこの画面はUITableViewで実装(= プログラミング)することが一般的なのですが、あまりUITableViewっぽくないため修正をお願いしたいです。
ちなみにCellをスワイプすることで削除ができるというUI/UXが一般的でおそらく戸井田さんも馴染みがあるのではないかと思っていますmm
(もしCellが分からなければ、学習する必要ありです)

履歴の肝心の金額がないため、追加した方がいいと思うのですがいかがでしょうか？

TODO:
以下のチケットを切ってください(issueに追加してください)
- コメントでいくつか質問したので回答いただけると嬉しいです。
- アプリのロゴを作成
- 必要であれば、UITableViewのキャッチアップ

**Comment by fuchi0741** [comment]
2,3枚目のヘッダー部分にどんな画面かがわかるといいかと思います！

**Comment by fuchi0741** [comment]
UI作成にあたり、実装がイメージできていない箇所があれば列挙していただけると嬉しいです！

**Comment by masayatoida** [comment]
@fuchi0741 

![image](https://user-images.githubusercontent.com/74668904/116997391-b1933600-ad17-11eb-9738-ff12b4e35af5.png)

UITableViewをキャッチアップして少し修正を加えたのですがいかがでしょうか。




UI作成の実装はやりながら不明点がでて色々不安ですが、今のところ大丈夫かなと思います。

**Comment by fuchi0741** [comment]
履歴の部分がまだTableViewぽくないため自分も不安なのですが、やりながら理解していくって形にしますか？？

それであれば、実際ポートフォリオ作成に移っても大丈夫かもです！
その前のプルリクエストを試しにやっていただきたいです！

**Comment by fuchi0741** [comment]
また、デフォルトブランチがmainであるためdevelopに変更していただきたいですー！

**Comment by fuchi0741** [comment]
@masayatoida

**Comment by masayatoida** [comment]
`Last login: Tue May  4 18:27:09 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
* master
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch develop
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
  develop
* master
rie@toidarikounoMacBook-Pro MoneyCalculator % git checkout develop
M	MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
Switched to branch 'develop'
rie@toidarikounoMacBook-Pro MoneyCalculator % `

**Comment by masayatoida** [comment]
`Last login: Tue May  4 18:27:09 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
* master
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch develop
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
  develop
* master
rie@toidarikounoMacBook-Pro MoneyCalculator % git checkout develop
M	MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
Switched to branch 'develop'
rie@toidarikounoMacBook-Pro MoneyCalculator % `

developに変更してみました！

**Comment by masayatoida** [comment]
`Last login: Tue May 4 18:27:09 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch

master
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch develop
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
develop
master
rie@toidarikounoMacBook-Pro MoneyCalculator % git checkout develop
M MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
Switched to branch 'develop'
rie@toidarikounoMacBook-Pro MoneyCalculator %`
developに変更してみました！

**Comment by masayatoida** [comment]
`
Last login: Tue May 4 18:27:09 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch

master
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch develop
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
develop
master
rie@toidarikounoMacBook-Pro MoneyCalculator % git checkout develop
M MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
Switched to branch 'develop'
rie@toidarikounoMacBook-Pro MoneyCalculator %
`
developに変更してみました！

**Comment by masayatoida** [comment]
@fuchi0741 

```
Last login: Tue May 4 18:27:09 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch

master
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch develop
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
develop
master
rie@toidarikounoMacBook-Pro MoneyCalculator % git checkout develop
M MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
Switched to branch 'develop'
rie@toidarikounoMacBook-Pro MoneyCalculator %

```


developに変更してみました！

**Comment by masayatoida** [comment]
@fuchi0741 
申し訳ありませんが、TableViewはやりながら勉強していきます！

**Comment by masayatoida** [comment]
@fuchi0741 

```
Last login: Tue May  4 18:27:09 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
* master
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch develop
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
  develop
* master
rie@toidarikounoMacBook-Pro MoneyCalculator % git checkout develop
M	MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
Switched to branch 'develop'
rie@toidarikounoMacBook-Pro MoneyCalculator % git push origin develop
Total 0 (delta 0), reused 0 (delta 0)
remote: 
remote: Create a pull request for 'develop' on GitHub by visiting:
remote:      https://github.com/masayatoida/MoneyCalcuator/pull/new/develop
remote: 
To https://github.com/masayatoida/MoneyCalcuator.git
 * [new branch]      develop -> develop
rie@toidarikounoMacBook-Pro MoneyCalculator % 
```
developに変更してみました！

**Comment by masayatoida** [comment]
@fuchi0741 
プルリクエストについて具体的な手順がよくわからず質問なのですが、
→ターミナルを操作してdevelopブランチに変更
→developブランチになにかしらの変更を加える
→プルリクエストをする
という手順だと思うのですが、ターミナルでdevelopブランチに変更した後

**developブランチになにかしらの変更を加える**

というのは、xcodeを直接変更してよろしいのですか？
（ターミナルでdevelopブランチがどこにできているのかがわかりません。とでもいうのでしょうか・・・）

例えばどのような変更をすれば良いでしょうか？

**Comment by fuchi0741** [comment]
@masayatoida いい感じですね！
言っていなかったため大変申し訳ないですが、developブランチはリモート上で変更していただきたいです！

添付画像の箇所です。
<img width="320" alt="スクリーンショット 2021-05-05 15 36 58" src="https://user-images.githubusercontent.com/50318372/117104800-befffd00-adb7-11eb-9f45-bf65446a96d5.png">

ローカルで毎回masterからdevelopに変更する方法はあまり推奨できないです。
理由は各メンバーがdevelopに変える必要があって、コストがかかるためです💡

わからない点があればぜひ聞いてくださいー！

**Comment by fuchi0741** [comment]
> プルリクエストについて具体的な手順がよくわからず質問なのですが、
> →ターミナルを操作してdevelopブランチに変更
> →developブランチになにかしらの変更を加える
> →プルリクエストをする
> という手順だと思うのですが、ターミナルでdevelopブランチに変更した後
> 
> developブランチになにかしらの変更を加える
> 
> というのは、xcodeを直接変更してよろしいのですか？
> （ターミナルでdevelopブランチがどこにできているのかがわかりません。とでもいうのでしょうか・・・）
> 
> 例えばどのような変更をすれば良いでしょうか？

gitflowに基づくのであれば、developブランチを作成するのはNGです🙏
developブランチからfeature/xxxブランチを作成する必要があります。

今回だとPRのお試しのため、**feature/test**というブランチをdevelopブランチから作ってから、xcodeで`print("test")`とどこかに実装をして、書いてください！

**Comment by fuchi0741** [comment]
developブランチの状態でxcodeでコードを書くと、developブランチの変更として認識されます！

**Comment by masayatoida** [comment]
@fuchi0741 
develop変更できました！

![image](https://user-images.githubusercontent.com/74668904/117218270-ce298e00-ae3d-11eb-84ba-6ffc552dbdd4.png)

**Comment by masayatoida** [comment]
feature/test ブランチ作成できました。
ただ、github のプルリクエストにfeature/testブランチがでないのはなぜでしょうか？


```
Last login: Tue May  4 18:27:09 on ttys000
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
* master
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch develop
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
  develop
* master
rie@toidarikounoMacBook-Pro MoneyCalculator % git checkout develop
M	MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
Switched to branch 'develop'
rie@toidarikounoMacBook-Pro MoneyCalculator % git push origin develop
Total 0 (delta 0), reused 0 (delta 0)
remote: 
remote: Create a pull request for 'develop' on GitHub by visiting:
remote:      https://github.com/masayatoida/MoneyCalcuator/pull/new/develop
remote: 
To https://github.com/masayatoida/MoneyCalcuator.git
 * [new branch]      develop -> develop
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch
* develop
  master
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch feature test
fatal: Not a valid object name: 'test'.
rie@toidarikounoMacBook-Pro MoneyCalculator % git branch feature/test
rie@toidarikounoMacBook-Pro MoneyCalculator % git checkout feature/test
M	MoneyCalculator.xcodeproj/project.xcworkspace/xcuserdata/rie.xcuserdatad/UserInterfaceState.xcuserstate
Switched to branch 'feature/test'
rie@toidarikounoMacBook-Pro MoneyCalculator % 

```





![image](https://user-images.githubusercontent.com/74668904/117570767-b89ab980-b106-11eb-93d2-66531f48355a.png)

**Comment by fuchi0741** [comment]
@masayatoida 
まずはbranchが正しく作成できているか確認をしていただきたいです！
コマンドは`git branch`で確認ができます😁

> github のプルリクエストにfeature/testブランチがでないのはなぜ
これは、pushしていないからでしょうか？

```
git add .
git commit -m "適当なコメント"
git push origin PRに出したいブランチ名
```

この一連を実行する必要がありますね！

**Comment by fuchi0741** [comment]
また、戸井田さんには転職後も見越して質問力も上げていきたいです！

質問がうまくできないと、先輩エンジニアから嫌われてしまう可能性があるため注意ですmm

次からで大丈夫なのですが、
質問する場合は、
- うまくいっていないこと
- 前提条件の共有(今回だとスクショ画像が該当 + でテキストがあった方が丁寧に感じるかも)
- うまくいかない原因の仮説(うまくいかない原因は何かを考える)
- 試してダメだったこと + ダメだと思う理由または仮説(アドバイス貰って、「それダメだったんですよね」と言われたら早く言ってよってなります笑 注意ですmm)
- 参考にした記事のリンク共有

**Comment by fuchi0741** [comment]
仮説を書くことで戸井田さんがどこが間違っているか、どこの知識に齟齬が発生しているかが明瞭になるため書きやすいです！

また、ぜひこのテンプレをうめながら調査するといいと思います！
意外と整理されて自己解決できる可能性が高まるのでおすすめです！

質問する場合はコピペで済みますし、テンプレ作成しながら調査だと質問の質が勝手に上がっているのでおすすめです！
(質問したくなってから文章考えると情報不足に陥る可能性が高いですmm)

**Comment by masayatoida** [comment]
@fuchi0741 
質問方法の件了解です！ご不便をおかけしてしまい申し訳ございません。

うまくいっていないこと
前提条件の共有
うまくいかない原因の仮説(うまくいかない原因は何かを考える)
試してダメだったこと + ダメだと思う理由または仮説
参考にした記事のリンク共有

こちらをテンプレートとして活用します。
ありがとうございます！

**Comment by fuchi0741** [comment]
> 質問方法の件了解です！ご不便をおかけしてしまい申し訳ございません。

いえいえ！ここは誰しも通る部分のため、このタイミングで把握していただければと思います！

**Comment by fuchi0741** [comment]
@masayatoida 
うーーん作成できてはいるのですが、プルリクエストは作成できていないですね😓

どういった手順で`feature/testのブランチ`を作成したか共有お願いできますか？

feature/test2というbranchをローカルで作成して、再度PRができるかチャレンジしてみましょう〜！
画像のPull Requestの欄に①となっていればいい感じなのですが
![image](https://user-images.githubusercontent.com/50318372/117893748-f6aa0000-b2f5-11eb-8721-838e710eecf9.png)

**Comment by masayatoida** [comment]
@fuchi0741 

![image](https://user-images.githubusercontent.com/74668904/118194927-2dfae700-b485-11eb-87e8-e990b107d5ad.png)

すみませんとりあえずプルリクエストはできました！
きちんと、プルリクエストの作成までできていなかったことが原因のようです。
また、プルリクエストは出せましたが、エラーが起きている状態でだしてしまいました・・・
（修正に時間がかかってしまいそうなのでとりあえずプルリクエストは出させていただきました）

**Comment by fuchi0741** [comment]
@masayatoida めっちゃいい感じですね！
おめでとうございます！
もう一旦このissueは閉じましょう！
