### ISSUE TITLE
一覧画面と履歴画面の違い

### ISSUE THREAD

**Issue by masayatoida** [masayatoida/MoneyCalcuator#4]
@fuchi0741

左上にある一覧に戻るですが、一覧画面がない気がするのですが。。。
そもそも一覧画面と履歴画面の違いってなんでしょうか？

→申し訳ございません、よくよく考えたら一覧画面は不要でした。
一覧画面のボタンは削除しました。

**Comment by fuchi0741** [comment]
@masayatoida このチケット閉じちゃってくださいー！
